name = "RTNL Pack"
author = "fwfy"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c71f692a85ea659762f4a9244601cc3faec549b112319f211c7cc4cabbf372d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.192"
