name = "RTNL Pack"
author = "fwfy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e656abee51f4e7aa732311ab3b1ac404fb293d23305081125fe00717872a54a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
