name = "RTNL Pack"
author = "fwfy"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de09a960423a838f0ed91e4a6a65902b6aef1074481ea477228f00180cb50cc1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
