name = "RTNL Pack"
author = "fwfy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2fc5c95241face366ea4fe78a4575b72590fff8bc0f3b90e490a4a80e6751b1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
