name = "RTNL Pack"
author = "fwfy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a4bb79a1acca633e744ca551f0981199ec42b5e88789cd14ab9a47c7d82b776"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
