name = "RTNL Pack"
author = "fwfy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b5260305dd795d5298cb618eed1d17f7d19094b76e51b3414ae1788b752127f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
