name = "RTNL Pack"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c32601f5e3dda7db7e570c9c616b6a481242e0821c73f251592548310c875c0b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
