name = "RTNL Pack"
author = "fwfy"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab78901ac1d1aedced55d9b5d9f5cc71988e8ea5925dd0a526df56f183f13e51"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.182"
