name = "RTNL Pack"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b69ccfe11bd21ffa0c829bc8e7a333ad9188175a2aeeea55b1c76ec7f0f137"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
