name = "RTNL Pack"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0ca96d76543e056b2466ae559324af098172cd38feabb251f1c62cc02560955d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
