name = "RTNL Pack"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9377695b52ef888beb6db36e0bea52c76514a8e022b056c80c4e00a4656fd6af"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
