name = "RTNL Pack"
author = "fwfy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9f767973fe21380a88b103e4f4228079eb1b05e22e887a83c6a5c9a675bddf"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.172"
