name = "RTNL Pack"
author = "fwfy"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "94e4ba22bf3a88994fe0550ec8771fa47bacc60f8ba8940609e2c2358791ed8c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.173"
